//! # Moat
//!
//! A non-custodial Solana vault that holds the funds and enforces the limits
//! while a TEE (the *keep*) holds the strategy and signs trade intents.
//!
//! The architecture is one sentence: **the keep decides, the moat permits.**
//! Nothing the keep produces is trusted; every intent is re-checked against
//! owner-set policy using the chain's own oracle reads before a lamport moves,
//! and the owner's withdrawal path never touches the keep at all.
//!
//! Component naming follows the fortress the project is named for — `keep`
//! (enclave), `portcullis` (the intent gate), `signet` (attestation), `drawbridge`
//! (deposits/withdrawals), `sortie` (one execution leg), `spyglass` (dashboard).
//! The instruction names stay conventional on purpose: cute selectors cost
//! reviewer trust, and this is a program that wants to be read.

use anchor_lang::prelude::*;

pub mod drawbridge;
pub mod errors;
pub mod events;
pub mod oracle;
pub mod portcullis;
pub mod signet;
pub mod state;

use errors::MoatError;
use events::{PolicyUpdated, SignetRotated, VaultOpened};
use state::{PolicyParams, Vault, VAULT_SEED};

// Glob, not named, re-exports: `#[program]` expands to paths like
// `crate::__client_accounts_deposit`, and those generated modules only come
// along with a glob. Naming the structs individually compiles everywhere except
// inside the macro, which is a confusing place to find out.
pub use drawbridge::*;
pub use portcullis::*;

// Generated by `cargo-build-sbf` into target/deploy/moat-keypair.json. Keep this in
// sync with Anchor.toml — the id is compiled into the binary.
declare_id!("FResswSN9ZiV6mCfhWJHowDY354km4cEgBXTYb1Ro7MQ");

/// Ceiling on how long one enclave registration stays valid: roughly seven days
/// of slots. An attestation is a statement about an enclave at a moment; a
/// registration that never expires quietly turns it into a statement about all
/// future moments.
pub const MAX_SIGNET_VALIDITY_SLOTS: u64 = 1_512_000;

#[program]
pub mod moat {
    use super::*;

    /// Create the vault PDA and install its first policy.
    pub fn open_vault(ctx: Context<OpenVault>, guardian: Pubkey, policy: PolicyParams) -> Result<()> {
        let vault = &mut ctx.accounts.vault;
        vault.bump = ctx.bumps.vault;
        vault.owner = ctx.accounts.owner.key();
        vault.guardian = guardian;

        // No enclave yet. Until `rotate_signet` runs, the vault can hold and
        // return funds but cannot trade — the safe state to be created in.
        vault.enclave_key = Pubkey::default();
        vault.enclave_measurement = [0u8; 32];
        vault.enclave_expiry_slot = 0;

        vault.policy_version = 0;
        policy.apply_to(vault)?; // bumps to 1

        vault.paused = false;
        vault.next_nonce = 0;
        vault.last_sortie_slot = 0;
        vault.day_index = 0;
        vault.day_notional = 0;

        emit!(VaultOpened {
            vault: vault.key(),
            owner: vault.owner,
            guardian: vault.guardian,
        });
        Ok(())
    }

    /// Replace the policy. Bumps `policy_version`, which immediately invalidates
    /// every intent the keep has already signed — tightening a limit takes
    /// effect now, not after the keep's queue drains.
    pub fn set_policy(ctx: Context<AdminOnly>, policy: PolicyParams) -> Result<()> {
        let vault = &mut ctx.accounts.vault;
        policy.apply_to(vault)?;

        emit!(PolicyUpdated {
            vault: vault.key(),
            policy_version: vault.policy_version,
            max_trade_notional: vault.max_trade_notional,
            max_daily_notional: vault.max_daily_notional,
            max_slippage_bps: vault.max_slippage_bps,
            mint_count: vault.mint_count,
            venue_count: vault.venue_count,
        });
        Ok(())
    }

    /// Register the enclave signing key, after the owner has checked its
    /// attestation.
    ///
    /// The TDX quote is verified **off-chain**: the owner (or their tooling)
    /// fetches the keep's quote, checks the signature chain and confirms the
    /// measurement matches the published build, then calls this. `measurement`
    /// is recorded so the value they approved is auditable on-chain afterwards.
    ///
    /// Verifying the quote on-chain would be strictly better and is the natural
    /// next step; it is a real piece of work (certificate chain parsing inside a
    /// compute budget), not a line of code, and pretending otherwise in a
    /// comment is how a scaffold ships as if it were finished.
    ///
    /// ## What a rotation does and does not invalidate
    ///
    /// Rotating to a **new** key kills every intent the retired key ever signed,
    /// for free: `execute_sortie` verifies against whatever key is registered
    /// *now*, so old signatures simply stop matching. That is the escape hatch
    /// for a compromised enclave.
    ///
    /// Re-registering the **same** key — extending an expiry — invalidates
    /// nothing, and outstanding signed intents stay spendable until they expire.
    /// If that is not what you want, call `set_policy` as well: bumping
    /// `policy_version` is the mechanism that strands in-flight intents.
    pub fn rotate_signet(
        ctx: Context<AdminOnly>,
        enclave_key: Pubkey,
        measurement: [u8; 32],
        valid_for_slots: u64,
    ) -> Result<()> {
        require_keys_neq!(enclave_key, Pubkey::default(), MoatError::NoEnclaveRegistered);
        require!(valid_for_slots > 0, MoatError::InvalidPolicy);
        require!(valid_for_slots <= MAX_SIGNET_VALIDITY_SLOTS, MoatError::InvalidPolicy);

        let clock = Clock::get()?;
        let vault = &mut ctx.accounts.vault;
        vault.enclave_key = enclave_key;
        vault.enclave_measurement = measurement;
        vault.enclave_expiry_slot =
            clock.slot.checked_add(valid_for_slots).ok_or(MoatError::MathOverflow)?;

        // Note: the nonce is deliberately *not* advanced here. Doing so would
        // look like it invalidates the retired key's outstanding intents, but it
        // only kills the single next one — the real protection is that
        // verification runs against the newly registered key. Leaving a
        // half-measure in place would be worse than leaving it out, because it
        // reads like a defence that is not one.

        emit!(SignetRotated {
            vault: vault.key(),
            enclave_key,
            enclave_measurement: measurement,
            expiry_slot: vault.enclave_expiry_slot,
        });
        Ok(())
    }

    pub fn deposit(ctx: Context<Deposit>, amount: u64) -> Result<()> {
        drawbridge::handle_deposit(ctx, amount)
    }

    /// Always available to the owner, paused or not. See `drawbridge`.
    pub fn withdraw(ctx: Context<Withdraw>, amount: u64) -> Result<()> {
        drawbridge::handle_withdraw(ctx, amount)
    }

    pub fn set_paused(ctx: Context<SetPaused>, paused: bool) -> Result<()> {
        drawbridge::handle_set_paused(ctx, paused)
    }

    /// Execute one leg of a keep-authorised plan. The portcullis.
    pub fn execute_sortie<'info>(
        ctx: Context<'info, ExecuteSortie<'info>>,
        intent_bytes: Vec<u8>,
        route_data: Vec<u8>,
    ) -> Result<()> {
        portcullis::handle_execute_sortie(ctx, intent_bytes, route_data)
    }
}

#[derive(Accounts)]
pub struct OpenVault<'info> {
    #[account(
        init,
        payer = owner,
        space = Vault::LEN,
        seeds = [VAULT_SEED, owner.key().as_ref()],
        bump
    )]
    pub vault: Account<'info, Vault>,
    #[account(mut)]
    pub owner: Signer<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct AdminOnly<'info> {
    #[account(mut, seeds = [VAULT_SEED, vault.owner.as_ref()], bump = vault.bump)]
    pub vault: Account<'info, Vault>,
    #[account(address = vault.owner @ MoatError::NotOwner)]
    pub owner: Signer<'info>,
}
